#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
hash -d abburan=/auto/users/bburan
hash -d auser=/auto/users
hash -d adata=/auto/data
hash -d acode=/auto/users/bburan/code

alias msql="mysql cell --user=david --password=nine1997 --host=hyrax.ohsu.edu"
alias remote="rdesktop -u bburan -p - -f -a -32"
alias win7remote="vboxheadless --startvm \"Windows 7\" --vrdeproperty VNCPassword=win7remote"

#VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
#export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
#source /usr/local/bin/virtualenvwrapper.sh 
 
export PATH="/home/bburan/bin/anaconda3/bin:$PATH"
export EDITOR="/usr/bin/vim"
